services:
  # PHP 7.4
  webapp-7-4:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./fpm/fpm-7.4
      dockerfile: Dockerfile
    image: webapp/php7.4
    container_name: webapp74_wsl
    ports:
      - "${XDEBUG_PORT_74}:9003" # xDebug
      - "9074:9074"              # Laravel Octane или кастомный HTTP порт
    volumes:
      - ./code:${SITE_PATH}
      - ./.env:${SITE_PATH}/.env
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    expose:
      - 9000
      - 9003
      - 9074
    networks:
      - app-net
    depends_on:
      - db_maria_wsl

  # PHP 8.1
  webapp-8-1:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./fpm/fpm-8.1
      dockerfile: Dockerfile
    image: webapp/php8.1
    container_name: webapp81_wsl
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${XDEBUG_PORT_81}:9003" # xDebug
      - "9081:9081"              # Laravel Octane или кастомный порт
    volumes:
      - ./code:${SITE_PATH}
      - ./.env:${SITE_PATH}/.env
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    expose:
      - 9000
      - 9003
      - 9081
    networks:
      - app-net
    depends_on:
      - db_maria_wsl

  # PHP 8.3
  webapp-8-3:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./fpm/fpm-8.3
      dockerfile: Dockerfile
    image: webapp/php8.3
    container_name: webapp83_wsl
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${XDEBUG_PORT_83}:9003"     # xDebug
      - "5185:5185"     # Vite
      - "9085:9083"     # Laravel Octane или другой HTTP порт
    volumes:
      - ./code:${SITE_PATH}:cached
      - ./.env:${SITE_PATH}/.env:cached
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
      CHOKIDAR_USEPOLLING: true
    expose:
      - 9000
      - 9003
      - 9083
    networks:
      - app-net
    depends_on:
      - db_maria_wsl

  # PHP 8.4
  webapp-8-4:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./fpm/fpm-8.4
      dockerfile: Dockerfile
    image: webapp/php8.4
    container_name: webapp84_wsl
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${XDEBUG_PORT_84}:9003" # xDebug
      - "9084:9084" # Laravel Octane или кастомный порт
    volumes:
      - ./code:${SITE_PATH}
      - ./.env:${SITE_PATH}/.env
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    expose:
      - 9000
      - 9003
      - 9084
    networks:
      - app-net
    depends_on:
      - db_maria_wsl

  vite:
    ports:
      - "5512:5512"
  # Nginx
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: webapp/nginx
    container_name: nginx_wsl
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "packs.local:host-gateway"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./code:/data:cached
      - ./nginx/hosts:/etc/nginx/sites-enabled:cached
    networks:
      - app-net
    depends_on:
      - webapp-7-4
      - webapp-8-1
      - webapp-8-3
      - webapp-8-4
      - db_maria_wsl

  # MariaDB
  db_maria_wsl:
    image: mariadb
    container_name: maria_db_wsl
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ./dbdata/mysqldata:/var/lib/mysql:cached
    networks:
      - app-net

  # Redis
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis_image
    container_name: redis_container_wsl
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "6378:6379"
    volumes:
      - ./redis/cache:/data/redis_cache
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-net
    depends_on:
      - db_maria_wsl

volumes:
  es_data:
    driver: local

networks:
  app-net:
    driver: bridge
