server {
    # указываем 80 порт для соединения
    listen 80;
    # listen [::]:80;
    server_name mc-club.local;
    root /data/mc-club.local/public;

    # из доки по ларавел - https://laravel.com/docs/11.x/deployment#nginx 
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php;

    location ~* .(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log off;
        log_not_found off;
        expires max;
    }
 #    # Vite dev assets
    location ^~ /build/ {
        proxy_pass http://webapp-8-4:5719;   # ← ИЗМЕНИТЬ
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ^~ /@vite {
        proxy_pass http://webapp-8-4:5719;   # ← ИЗМЕНИТЬ
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ^~ /ws {
        proxy_pass http://webapp-8-4:5719;   # ← ИЗМЕНИТЬ
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # location /public/ {
    #     alias /data/mc-club.local/public/build/; # Путь к папке build
    #     access_log off;
    #     expires max;
    # }    
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # и наконец правило обращения к php-fpm
    location ~* .php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass webapp84_wsl:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
    error_log /var/log/nginx/mc-club_error.log;
    access_log /var/log/nginx/mc-club_access.log;
}
